"""SQLAlchemy ORM models for StrategosAI."""

import datetime
from sqlalchemy import Column, Integer, String, Text, Float, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from database import Base


class Company(Base):
    """User's own company — the DNA baseline."""
    __tablename__ = "companies"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(255), nullable=False)
    url = Column(String(512), nullable=False)
    summary = Column(Text, default="")
    features = Column(JSON, default=list)        # [{name, description, category}]
    icp = Column(JSON, default=dict)             # {segments, personas, pain_points}
    positioning = Column(JSON, default=dict)      # {value_prop, differentiators, market_pos}
    pricing = Column(JSON, default=dict)          # {model, tiers, notes}
    raw_profile = Column(Text, default="")        # long-form summary for embedding
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitors = relationship("Competitor", back_populates="company", cascade="all, delete-orphan")


class Competitor(Base):
    """A competitor being analyzed."""
    __tablename__ = "competitors"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(255), default="")
    url = Column(String(512), nullable=False)
    status = Column(String(50), default="pending")  # pending, crawling, crawled, analyzing, done
    page_count = Column(Integer, default=0)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    company = relationship("Company", back_populates="competitors")
    pages = relationship("CrawledPage", back_populates="competitor", cascade="all, delete-orphan")
    signals = relationship("Signal", back_populates="competitor", cascade="all, delete-orphan")
    plan_tasks = relationship("PlanTask", back_populates="competitor", cascade="all, delete-orphan")
    monitor_jobs = relationship("MonitorJob", back_populates="competitor", cascade="all, delete-orphan")
    change_alerts = relationship("ChangeAlert", back_populates="competitor", cascade="all, delete-orphan")
    review_data = relationship("ReviewData", back_populates="competitor", cascade="all, delete-orphan")
    ad_data = relationship("AdData", back_populates="competitor", cascade="all, delete-orphan")
    community_intel = relationship("CommunityIntelData", back_populates="competitor", cascade="all, delete-orphan")


class CrawledPage(Base):
    """A single scraped page from a competitor's site."""
    __tablename__ = "crawled_pages"

    id = Column(Integer, primary_key=True, autoincrement=True)
    url = Column(String(512), nullable=False)
    title = Column(String(512), default="")
    content_md = Column(Text, default="")         # cleaned markdown content
    page_type = Column(String(100), default="")   # Pricing, Features, About, Blog, Enterprise, etc.
    strategic_score = Column(Integer, default=0)   # 0-100
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor", back_populates="pages")


class Signal(Base):
    """An intelligence signal extracted by the analyst engine."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_type = Column(String(50), nullable=False)  # threat, opportunity
    category = Column(String(100), default="")         # feature_gap, pricing, market_shift, etc.
    title = Column(String(512), nullable=False)
    description = Column(Text, default="")
    severity = Column(String(50), default="moderate")  # existential, moderate, minor
    relevance = Column(Float, default=0.0)              # 0-100
    confidence = Column(Float, default=0.0)             # 0-100
    evidence = Column(JSON, default=list)               # [{source_url, quote, page_type}]
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor", back_populates="signals")


class PlanTask(Base):
    """A tactical roadmap task generated by the planner agent."""
    __tablename__ = "plan_tasks"

    id = Column(Integer, primary_key=True, autoincrement=True)
    week = Column(Integer, nullable=False)             # 1-4
    title = Column(String(512), nullable=False)
    description = Column(Text, default="")
    task_type = Column(String(50), default="")         # defensive, offensive
    owner = Column(String(255), default="")
    priority = Column(String(50), default="medium")    # critical, high, medium, low
    success_metric = Column(String(512), default="")
    evidence_url = Column(String(512), default="")
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor", back_populates="plan_tasks")


class MonitorJob(Base):
    """Scheduled monitoring job for a competitor."""
    __tablename__ = "monitor_jobs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False, unique=True)
    schedule = Column(String(20), default="weekly")        # 'daily' or 'weekly'
    last_run = Column(DateTime, nullable=True)
    next_run = Column(DateTime, nullable=True)
    is_active = Column(Integer, default=0)                  # 0=False, 1=True (SQLite compat)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor", back_populates="monitor_jobs")


class ChangeAlert(Base):
    """A change alert generated by the monitoring system."""
    __tablename__ = "change_alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False)
    detected_at = Column(DateTime, default=datetime.datetime.utcnow)
    new_signals = Column(JSON, default=list)               # [{title, signal_type, severity}]
    disappeared_signals = Column(JSON, default=list)       # [{title, signal_type, severity}]
    severity_changes = Column(JSON, default=list)           # [{title, old_severity, new_severity}]
    summary = Column(Text, default="")
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor", back_populates="change_alerts")


class ReviewData(Base):
    """Review platform data (G2, Trustpilot) for a competitor."""
    __tablename__ = "review_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False)
    source = Column(String(50), default="")           # "g2" | "trustpilot"
    url = Column(String(512), default="")
    overall_rating = Column(Float, default=0.0)
    review_count = Column(Integer, default=0)
    rating_distribution = Column(JSON, default=dict)   # {"5": 60, "4": 15, ...}
    likes = Column(JSON, default=list)                 # list of strings
    dislikes = Column(JSON, default=list)              # list of strings
    use_cases = Column(JSON, default=list)             # list of strings
    negative_themes = Column(JSON, default=list)       # list of strings
    reviewer_segments = Column(JSON, default=list)     # list of strings
    recent_reviews = Column(JSON, default=list)        # list of review objects
    scraper_status = Column(String(50), default="success")  # success | blocked | not_found | error
    scraped_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor", back_populates="review_data")


class AdData(Base):
    """Ad library data (Meta, Google) for a competitor."""
    __tablename__ = "ad_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False)
    source = Column(String(50), default="")           # "meta_ads" | "google_ads"
    url = Column(String(512), default="")
    total_ads_found = Column(Integer, default=0)
    ads = Column(JSON, default=list)                  # list of ad objects
    cta_distribution = Column(JSON, default=dict)     # {"Sign Up": 6, ...}
    top_messaging_themes = Column(JSON, default=list)
    top_keywords = Column(JSON, default=list)
    headline_patterns = Column(JSON, default=list)
    scraper_status = Column(String(50), default="success")  # success | blocked | not_found | error
    scraped_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor", back_populates="ad_data")


class CommunityIntelData(Base):
    """Community intelligence data (HackerNews, Reddit Deep) for a competitor."""
    __tablename__ = "community_intel_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    competitor_id = Column(Integer, ForeignKey("competitors.id"), nullable=False)
    source = Column(String(50), default="")            # "hackernews" | "reddit_deep"
    total_mentions = Column(Integer, default=0)
    sentiment_score = Column(Integer, default=50)       # 0-100, 50 = neutral
    sentiment_breakdown = Column(JSON, default=dict)    # {positive: N, negative: N, neutral: N}
    positive_comments = Column(JSON, default=list)      # list of {text, url, points, ...}
    negative_comments = Column(JSON, default=list)      # list of {text, url, points, ...}
    reviews = Column(JSON, default=list)                # reddit_deep: reviews
    complaints = Column(JSON, default=list)             # reddit_deep: complaints
    comparisons = Column(JSON, default=list)            # reddit_deep: comparison posts
    switching_signals = Column(JSON, default=list)      # list of {signal, url, ...}
    top_subreddits = Column(JSON, default=list)         # reddit_deep: [{name, mentions}]
    scraper_status = Column(String(50), default="success")
    scraped_at = Column(DateTime, default=datetime.datetime.utcnow)

    competitor = relationship("Competitor", back_populates="community_intel")
